name: Deploy workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: sudo apt-get update

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
        
      - name: Build app
        run: |
          npm run build

      - name: Copy build to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -zr --delete
          path: dist/
          remote_path: ${{ vars.PROJECT_PATH }}/dist/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Start application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source ~/.nvm/nvm.sh
            cd ${{ vars.PROJECT_PATH }}
            git reset --hard HEAD
            git pull
            npm install

            # Check if PM2 is already running the app
            pm2 describe ${{ vars.PROJECT_NAME }} > /dev/null 2>&1
            RUNNING=$?

            if [ "${RUNNING}" -ne 0 ]; then
                # Start new
              pm2 start dist/main.js --name ${{ vars.PROJECT_NAME }} -i 1
            else
              pm2 reload ${{ vars.PROJECT_NAME }} --wait-ready --listen-timeout 300 --update-env
            fi

      - name: Cleanup
        run: |
          rm -rf ~/.ssh